// Sample XHTML content for ContentPreview testing
// Using TypeScript module to avoid template string parsing issues

export const navigationContent = [
  '<?xml version="1.0" encoding="UTF-8"?>',
  '<!DOCTYPE html>',
  '<html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops">',
  '<head>',
  '  <title>Table of Contents</title>',
  '  <style>',
  '    body { font-family: "Times New Roman", serif; margin: 0; padding: 16px; }',
  '    nav { padding: 0; }',
  '    ol { padding-left: 20px; margin: 0; }',
  '    li { margin: 8px 0; }',
  '    a { color: #0066cc; text-decoration: none; }',
  '    a:hover { text-decoration: underline; }',
  '    .chapter-title { font-weight: bold; }',
  '  </style>',
  '</head>',
  '<body>',
  '  <nav epub:type="toc" role="navigation">',
  '    <h1>Table of Contents</h1>',
  '    <ol>',
  '      <li><a href="chapter01.xhtml" class="chapter-title">Chapter 1: The Adventure Begins</a></li>',
  '      <li><a href="chapter02.xhtml" class="chapter-title">Chapter 2: Into the Unknown</a></li>',
  '      <li><a href="chapter03.xhtml" class="chapter-title">Chapter 3: Meeting New Friends</a></li>',
  '      <li><a href="chapter04.xhtml" class="chapter-title">Chapter 4: The Challenge</a></li>',
  '      <li><a href="chapter05.xhtml" class="chapter-title">Chapter 5: Resolution</a></li>',
  '    </ol>',
  '  </nav>',
  '</body>',
  '</html>'
].join('\n');

export const chapterContent = [
  '<?xml version="1.0" encoding="UTF-8"?>',
  '<!DOCTYPE html>',
  '<html xmlns="http://www.w3.org/1999/xhtml">',
  '<head>',
  '  <title>Chapter 1: The Adventure Begins</title>',
  '  <style>',
  '    body { font-family: Georgia, serif; line-height: 1.6; margin: 0; padding: 24px; }',
  '    h1 { color: #2c3e50; margin-bottom: 24px; font-size: 2em; }',
  '    p { margin: 16px 0; text-align: justify; }',
  '    .drop-cap { float: left; font-size: 3em; line-height: 1; margin: 0 8px 0 0; }',
  '  </style>',
  '</head>',
  '<body>',
  '  <h1>Chapter 1: The Adventure Begins</h1>',
  '  <p><span class="drop-cap">I</span>t was a bright and sunny morning when our story begins. The protagonist, feeling restless and eager for adventure, decided that today would be different from all the others.</p>',
  '  <p>Walking down the cobblestone path that led away from the village, they noticed something peculiar in the distance. A shimmering light seemed to dance between the trees, calling out like a beacon of mystery.</p>',
  '  <p>"What could that be?" they wondered aloud, quickening their pace toward the unknown. Little did they know that this simple curiosity would lead to the most extraordinary adventure of their lifetime.</p>',
  '  <p>The forest grew denser as they approached, but the mysterious light continued to beckon. With each step, the anticipation grew stronger, and the sense that something magical was about to happen filled the air.</p>',
  '</body>',
  '</html>'
].join('\n');

export const complexContent = [
  '<?xml version="1.0" encoding="UTF-8"?>',
  '<!DOCTYPE html>',
  '<html xmlns="http://www.w3.org/1999/xhtml">',
  '<head>',
  '  <title>Interactive Content Example</title>',
  '  <style>',
  '    body { font-family: Arial, sans-serif; margin: 0; padding: 20px; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); }',
  '    .container { background: white; border-radius: 10px; padding: 30px; box-shadow: 0 10px 30px rgba(0,0,0,0.2); }',
  '    h1 { color: #333; text-align: center; margin-bottom: 30px; animation: fadeIn 2s ease-in; }',
  '    .interactive-demo { display: flex; gap: 20px; margin: 20px 0; }',
  '    .button { background: #4CAF50; color: white; padding: 12px 24px; border: none; border-radius: 5px; cursor: pointer; transition: all 0.3s; }',
  '    .button:hover { background: #45a049; transform: translateY(-2px); }',
  '    .color-box { width: 50px; height: 50px; border-radius: 50%; margin: 10px; transition: transform 0.3s; cursor: pointer; }',
  '    .color-box:hover { transform: scale(1.2); }',
  '    #output { background: #f0f0f0; padding: 15px; border-radius: 5px; margin-top: 20px; min-height: 50px; }',
  '    @keyframes fadeIn { from { opacity: 0; transform: translateY(20px); } to { opacity: 1; transform: translateY(0); } }',
  '  </style>',
  '</head>',
  '<body>',
  '  <div class="container">',
  '    <h1>Interactive Content Demo</h1>',
  '    <p>This demonstrates complex content with CSS animations and JavaScript interactions:</p>',
  '    ',
  '    <div class="interactive-demo">',
  '      <button class="button" onclick="changeText()">Change Text</button>',
  '      <button class="button" onclick="addColor()">Add Color</button>',
  '      <button class="button" onclick="animate()">Animate</button>',
  '    </div>',
  '    ',
  '    <div style="display: flex; flex-wrap: wrap;">',
  '      <div class="color-box" style="background: #ff6b6b;" onclick="selectColor(\'red\')"></div>',
  '      <div class="color-box" style="background: #4ecdc4;" onclick="selectColor(\'teal\')"></div>',
  '      <div class="color-box" style="background: #45b7d1;" onclick="selectColor(\'blue\')"></div>',
  '      <div class="color-box" style="background: #f9ca24;" onclick="selectColor(\'yellow\')"></div>',
  '    </div>',
  '    ',
  '    <div id="output">Click buttons above to see interactive content in action!</div>',
  '  </div>',
  '  ',
  '  <script>',
  '    function changeText() {',
  '      document.getElementById(\'output\').innerHTML = \'Text changed at \' + new Date().toLocaleTimeString() + \'!\';',
  '    }',
  '    ',
  '    function addColor() {',
  '      const colors = [\'#ff6b6b\', \'#4ecdc4\', \'#45b7d1\', \'#f9ca24\', \'#a55eea\', \'#26de81\'];',
  '      const randomColor = colors[Math.floor(Math.random() * colors.length)];',
  '      document.getElementById(\'output\').style.background = randomColor;',
  '      document.getElementById(\'output\').innerHTML = \'Background color changed!\';',
  '    }',
  '    ',
  '    function selectColor(color) {',
  '      document.getElementById(\'output\').innerHTML = \'You selected: \' + color;',
  '    }',
  '    ',
  '    function animate() {',
  '      document.querySelector(\'h1\').style.animation = \'fadeIn 1s ease-in\';',
  '      document.getElementById(\'output\').innerHTML = \'Animation triggered!\';',
  '    }',
  '  </script>',
  '</body>',
  '</html>'
].join('\n');

export const malformedContent = [
  '<?xml version="1.0" encoding="UTF-8"?>',
  '<!DOCTYPE html>',
  '<html xmlns="http://www.w3.org/1999/xhtml">',
  '<head>',
  '  <title>Malformed Content Test</title>',
  '  <style>',
  '    body { font-family: Arial, sans-serif; margin: 20px; color: #333; }',
  '    .error-demo { background: #ffebee; border: 1px solid #f44336; padding: 15px; border-radius: 5px; }',
  '  </style>',
  '</head>',
  '<body>',
  '  <h1>Malformed XHTML Test</h1>',
  '  <div class="error-demo">',
  '    <p>This content contains intentional errors to test error handling:</p>',
  '    <div class="unclosed-div">',
  '      <p>This div is never closed...',
  '      <span class="unclosed-span">This span is never closed either...',
  '    <div>',
  '    <p>Missing closing tags above should be handled gracefully.</p>',
  '    <!-- Unclosed comment',
  '    <script>',
  '      console.log("Potentially problematic script");',
  '      missing closing tag',
  '    <p>Content after malformed script tag.</p>',
  '  </div>',
  '</body>',
  '<!-- Missing closing html tag -->'
].join('\n');