/**
 * Story-side project seeding harness.
 *
 * Builds the same service graph App.svelte wires at boot, creates a real
 * project in the real storage backend (OPFS or IndexedDB — whatever the
 * story browser supports), and points the app at it via the persisted
 * `seedhtml_app_workspace_id` key. A story can then mount the real <App/> and
 * it restores onto the seeded project exactly as a browser reload would —
 * no injection seam into App required.
 *
 * Isolation: every call creates its own workspace (ids are generated by
 * WorkspaceService); `cleanup()` deletes it and clears the persisted keys.
 * Call cleanup in the story's teardown (or leave it for manual inspection
 * while developing a story).
 */

import { FileStorageAPI } from '../../lib/storage';
import { WorkspaceService } from '../../lib/services/workspace/workspace.service';
import type { WorkspaceState } from '../../lib/services/workspace/workspace.service';
import { SpineService } from '../../lib/services/spine/spine.service';
import { ExtensionManager } from '../../lib/extensions/extension-manager';
import { loadExtensionCatalog } from '../../lib/extensions/extension-catalog';
import { addTransform } from '../../lib/settings/dom-transforms';
import pageCSS from '../../assets/universal/page.css?raw';
import transformTextJS from '../../assets/universal/transformText.js?raw';
import transformDomJS from '../../assets/universal/transformDom.js?raw';

const WORKSPACE_ID_KEY = 'seedhtml_app_workspace_id';
const NAV_VIEW_KEY = 'seedhtml_nav_current_view';

const BASE_TEXT_TRANSFORM = 'SOURCE/scripts/transformText.js';
const BASE_DOM_TRANSFORM = 'SOURCE/scripts/transformDom.js';

export interface SeedChapter {
  title: string;
  /** Plain-text chapter source; the app transforms it when the chapter opens. */
  sourceText: string;
}

export interface SeedProjectOptions {
  title?: string;
  author?: string;
  /** BCP-47 tag; single language for the seeded book. */
  language?: string;
  chapters?: SeedChapter[];
  /** View the app should open on (persisted nav state), e.g. 'spine'. */
  view?: string;
  /**
   * Catalog extension ids to install into the project (e.g. ['djot', 'prism']),
   * in the order they should stack. The first one that provides a text
   * transform becomes the project's text_transform (like picking a format on
   * create); every DOM transform is appended to dom_transforms. The extension
   * files are fetched from the same-origin `/extensions/` the app uses, so this
   * works in Storybook and in test:stories.
   *
   * Note: EPUB assets an extension carries (e.g. a Prism theme CSS) are not yet
   * registered into the manifest here — enough for the settings form and for
   * transforms that highlight structurally, not for asset-dependent styling.
   */
  extensions?: string[];
}

export interface SeededProject {
  workspaceId: string;
  workspace: WorkspaceState;
  fileStorage: FileStorageAPI;
  workspaceService: WorkspaceService;
  spineService: SpineService;
  /** Delete the seeded workspace and clear the persisted keys. */
  cleanup: () => Promise<void>;
}

const DEFAULT_CHAPTERS: SeedChapter[] = [
  {
    title: 'Chapter One',
    sourceText: '# Chapter One\n\nA seeded chapter for workflow stories.\n\nEdit me.',
  },
  {
    title: 'Chapter Two',
    sourceText:
      '# Chapter Two\n\nA second chapter, so reordering and navigation have something to work with.',
  },
];

export async function seedProject(options: SeedProjectOptions = {}): Promise<SeededProject> {
  const {
    title = 'Storybook Seeded Book',
    author = 'Storybook',
    language = 'en',
    chapters = DEFAULT_CHAPTERS,
    view,
    extensions = [],
  } = options;

  const fileStorage = FileStorageAPI.getInstance();
  await fileStorage.init();

  const workspaceService = new WorkspaceService(fileStorage);
  const spineService = new SpineService(workspaceService);

  // Idempotent reruns: the story browser's storage persists across runs, so
  // clear out earlier seeds of the same book before creating this one.
  const existing = await workspaceService.listWorkspaces();
  for (const stale of existing.filter(w => w.title === title)) {
    try {
      await workspaceService.deleteWorkspace(stale.id);
    } catch {
      // best-effort
    }
  }

  let workspace = await workspaceService.createWorkspace({
    title,
    language: [language],
    identifier: `urn:uuid:${crypto.randomUUID()}`,
    creator: [{ name: author, roles: [] }],
  });

  for (const chapter of chapters) {
    const result = await spineService.addChapter(workspace, {
      title: chapter.title,
      sourceText: chapter.sourceText,
      createSourceFile: true,
      linear: true,
    });
    workspace = result.updatedWorkspace;
  }

  // Extensions need the project's structural base (the default transform
  // scripts they stack onto, plus a settings file wiring the pipeline). Only
  // write it when extensions are requested — the app tolerates its absence for
  // plain seeds, and skipping the extra writes keeps the common seed fast (it's
  // on the hot path of every seeded story in the parallel test suite).
  if (extensions.length > 0) {
    const wsId = workspace.id;
    await fileStorage.writeTextFile(wsId, 'OEBPS/Styles/page.css', pageCSS);
    await fileStorage.writeTextFile(wsId, BASE_TEXT_TRANSFORM, transformTextJS);
    await fileStorage.writeTextFile(wsId, BASE_DOM_TRANSFORM, transformDomJS);
    await fileStorage.writeTextFile(wsId, 'SOURCE/preview/head.xml', '');

    let textTransform = BASE_TEXT_TRANSFORM;
    let domTransforms = [BASE_DOM_TRANSFORM];

    // Install each extension from the same-origin catalog and wire its
    // transforms into the settings, mirroring App.installCatalogExtension.
    const extensionManager = new ExtensionManager(fileStorage);
    const catalog = await loadExtensionCatalog();
    for (const id of extensions) {
      const entry = catalog.find(e => e.id === id);
      if (!entry) throw new Error(`seedProject: extension '${id}' not in the catalog`);
      await extensionManager.importCatalogExtension(wsId, entry);
      for (const file of entry.domTransforms) {
        domTransforms = addTransform(domTransforms, `SOURCE/extensions/${id}/${file}`);
      }
      if (entry.textTransforms.length > 0) {
        textTransform = `SOURCE/extensions/${id}/${entry.textTransforms[0]}`;
      }
    }

    await fileStorage.writeTextFile(
      wsId,
      'SOURCE/settings.json',
      JSON.stringify(
        {
          version: '1.0.0',
          text_transform: textTransform,
          dom_transforms: domTransforms,
          preview: {
            autoUpdate: { responsive: true, device: true, pdf: false },
            head: 'preview/head.xml',
            includeHead: { responsive: true, device: false, pdf: false },
          },
        },
        null,
        2
      )
    );
  }

  localStorage.setItem(WORKSPACE_ID_KEY, workspace.id);
  if (view) localStorage.setItem(NAV_VIEW_KEY, view);

  // Neutralise persisted UI state other stories may have left behind (a
  // collapsed sidebar would hide the section buttons from this story's App
  // mount).
  localStorage.setItem('seedhtml_sidebar_expanded', 'true');
  localStorage.setItem('seedhtml_sidebar_project_expanded', 'true');
  localStorage.removeItem('seedhtml_sidebar_section');

  return {
    workspaceId: workspace.id,
    workspace,
    fileStorage,
    workspaceService,
    spineService,
    cleanup: async () => {
      localStorage.removeItem(WORKSPACE_ID_KEY);
      localStorage.removeItem(NAV_VIEW_KEY);
      try {
        await workspaceService.deleteWorkspace(workspace.id);
      } catch {
        // Already gone (e.g. the story deleted the project as part of the
        // workflow) — cleanup stays best-effort.
      }
    },
  };
}
