/**
 * Story-side project seeding harness.
 *
 * Builds the same service graph App.svelte wires at boot, creates a real
 * project in the real storage backend (OPFS or IndexedDB — whatever the
 * story browser supports), and points the app at it via the persisted
 * `editme_app_workspace_id` key. A story can then mount the real <App/> and
 * it restores onto the seeded project exactly as a browser reload would —
 * no injection seam into App required.
 *
 * Isolation: every call creates its own workspace (ids are generated by
 * WorkspaceService); `cleanup()` deletes it and clears the persisted keys.
 * Call cleanup in the story's teardown (or leave it for manual inspection
 * while developing a story).
 */

import { FileStorageAPI } from '../../lib/storage';
import { WorkspaceService } from '../../lib/services/workspace/workspace.service';
import type { WorkspaceState } from '../../lib/services/workspace/workspace.service';
import { SpineService } from '../../lib/services/spine/spine.service';

const WORKSPACE_ID_KEY = 'editme_app_workspace_id';
const NAV_VIEW_KEY = 'editme_nav_current_view';

export interface SeedChapter {
  title: string;
  /** Plain-text chapter source; the app transforms it when the chapter opens. */
  sourceText: string;
}

export interface SeedProjectOptions {
  title?: string;
  author?: string;
  /** BCP-47 tag; single language for the seeded book. */
  language?: string;
  chapters?: SeedChapter[];
  /** View the app should open on (persisted nav state), e.g. 'spine'. */
  view?: string;
}

export interface SeededProject {
  workspaceId: string;
  workspace: WorkspaceState;
  fileStorage: FileStorageAPI;
  workspaceService: WorkspaceService;
  spineService: SpineService;
  /** Delete the seeded workspace and clear the persisted keys. */
  cleanup: () => Promise<void>;
}

const DEFAULT_CHAPTERS: SeedChapter[] = [
  {
    title: 'Chapter One',
    sourceText: '# Chapter One\n\nA seeded chapter for workflow stories.\n\nEdit me.',
  },
  {
    title: 'Chapter Two',
    sourceText: '# Chapter Two\n\nA second chapter, so reordering and navigation have something to work with.',
  },
];

export async function seedProject(options: SeedProjectOptions = {}): Promise<SeededProject> {
  const {
    title = 'Storybook Seeded Book',
    author = 'Storybook',
    language = 'en',
    chapters = DEFAULT_CHAPTERS,
    view,
  } = options;

  const fileStorage = FileStorageAPI.getInstance();
  await fileStorage.init();

  const workspaceService = new WorkspaceService(fileStorage);
  const spineService = new SpineService(workspaceService);

  // Idempotent reruns: the story browser's storage persists across runs, so
  // clear out earlier seeds of the same book before creating this one.
  const existing = await workspaceService.listWorkspaces();
  for (const stale of existing.filter(w => w.title === title)) {
    try {
      await workspaceService.deleteWorkspace(stale.id);
    } catch {
      // best-effort
    }
  }

  let workspace = await workspaceService.createWorkspace({
    title,
    language: [language],
    identifier: `urn:uuid:${crypto.randomUUID()}`,
    creator: [{ name: author, roles: [] }],
  });

  for (const chapter of chapters) {
    const result = await spineService.addChapter(workspace, {
      title: chapter.title,
      sourceText: chapter.sourceText,
      createSourceFile: true,
      linear: true,
    });
    workspace = result.updatedWorkspace;
  }

  localStorage.setItem(WORKSPACE_ID_KEY, workspace.id);
  if (view) localStorage.setItem(NAV_VIEW_KEY, view);

  return {
    workspaceId: workspace.id,
    workspace,
    fileStorage,
    workspaceService,
    spineService,
    cleanup: async () => {
      localStorage.removeItem(WORKSPACE_ID_KEY);
      localStorage.removeItem(NAV_VIEW_KEY);
      try {
        await workspaceService.deleteWorkspace(workspace.id);
      } catch {
        // Already gone (e.g. the story deleted the project as part of the
        // workflow) — cleanup stays best-effort.
      }
    },
  };
}
